name: location_tracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+1.1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your app needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  persistent_bottom_nav_bar: ^6.2.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.1.5
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  flutter_background_service: ^5.1.0
  geolocator: ^14.0.2
  another_flushbar: ^1.12.30
  google_sign_in: ^6.1.2
  firebase_auth: ^6.1.2
  device_preview: ^1.3.1
  permission_handler: ^11.3.0
  dropdown_search: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
